<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ADS67" name="exe.HS_Record_Type_DataValidation_003" tests="5" failures="0" timestamp="30 Jun 2017 05:05:40 GMT" time="0.467" errors="1">
  <testcase name="Record_Type_AS_Debt_Cancel" time="0.124" classname="exe.HS_Record_Type_DataValidation_003"/>
  <testcase name="Record_Type_AS_HS_Price_Increase" time="0.078" classname="exe.HS_Record_Type_DataValidation_003"/>
  <testcase name="Record_Type_AS_NULL" time="0.078" classname="exe.HS_Record_Type_DataValidation_003"/>
  <testcase name="Record_Type_AS_HS_DownGrade" time="0.093" classname="exe.HS_Record_Type_DataValidation_003">
    <error type="junit.framework.AssertionFailedError" message="HS_DownGrade counts are Not Equal expected:&lt;14&gt; but was:&lt;13&gt;">
      <![CDATA[junit.framework.AssertionFailedError: HS_DownGrade counts are Not Equal expected:<14> but was:<13>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.HS_Record_Type_DataValidation_003.Record_Type_AS_HS_DownGrade(HS_Record_Type_DataValidation_003.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- Record_Type_AS_HS_DownGrade -->
  <testcase name="Record_Type_AS_Debt_Delinquent_Letter" time="0.094" classname="exe.HS_Record_Type_DataValidation_003"/>
</testsuite> <!-- exe.HS_Record_Type_DataValidation_003 -->
